version: '3'
services:
  db:
    image: postgres:15-alpine # 2023/10/31 GCPで15が最新だったので
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5333:5432
    volumes:
      - ./.postgres15/postgres_data:/var/lib/postgresql/data
