import "./globals.css";
import type { Metadata } from "next";
import Header from "./_components/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="ja">
      <body className="bg-gray-100">
        <Header authenticated={!!session} />
        <div className="mt-4">{children}</div>
      </body>
    </html>
  );
}
